name: Terraform CI

on:
  workflow_call:
  pull_request:
    paths:
      - 'terraform/**'
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fmt-validate:
    name: fmt & validate
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TF_IN_AUTOMATION: 'true'
    strategy:
      fail-fast: false
      matrix:
        working_directory:
          - terraform/configurations/cloudflare-session-operator
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.6'
          cli_config_credentials_token: ''

      - name: Terraform fmt (check)
        run: terraform -chdir=${{ matrix.working_directory }} fmt -check -recursive

      - name: Terraform init (no backend)
        run: terraform -chdir=${{ matrix.working_directory }} init -backend=false

      - name: Terraform validate
        run: terraform -chdir=${{ matrix.working_directory }} validate -no-color


